const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const cors = require('cors');
const nodemailer = require('nodemailer');
const cron = require('node-cron'); // Ensure you run: npm install node-cron
const { generateNetworkData, addZone, removeZone } = require('./controllers/simulation');

const app = express();
app.use(cors());
app.use(express.json());

// --- 1. EMAIL CONFIGURATION ---
// Replace with your actual Gmail and the 16-character App Password
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: 'taufikali7867@gmail.com', 
        pass: 'pzexwjvvosbplvsu' 
    }
});

// Verify email service on startup
transporter.verify((error, success) => {
    if (error) {
        console.log("❌ Email Service Error:", error);
    } else {
        console.log("✅ Email Service is ready to send reports");
    }
});

// --- 2. AUTOMATION: Monthly Energy Report ---
// Schedules a task to run at 00:00 on the 1st day of every month
cron.schedule('0 0 1 * *', async () => {
    console.log("📊 [AUTOMATION] Generating Monthly ESG Report...");
    
    const reportData = generateNetworkData();
    const totalROI = (reportData.globalMetrics.lifetimeKwhSaved * 8.5).toFixed(2); // Pune commercial rate
    
    const mailOptions = {
        from: 'taufikali7867@gmail.com',
        to: 'taufikali7867@gmail.com',
        subject: 'ClimateSense: Monthly Energy & ROI Report',
        html: `
            <div style="font-family: sans-serif; padding: 20px; border: 1px solid #10b981; border-radius: 10px;">
                <h2 style="color: #10b981;">Monthly Sustainability Update</h2>
                <p>Your mesh network successfully optimized office cooling for the past 30 days.</p>
                <hr/>
                <p><strong>Total Energy Saved:</strong> ${reportData.globalMetrics.avgEnergySaved}%</p>
                <p><strong>CO2 Reduced:</strong> ${reportData.globalMetrics.co2ReducedKg} kg</p>
                <p><strong>Financial ROI:</strong> ₹${totalROI}</p>
                <hr/>
                <p style="font-size: 0.8rem; color: #666;">This is an automated report generated by ClimateSense IONET.</p>
            </div>
        `
    };

    try {
        await transporter.sendMail(mailOptions);
        console.log("✅ [AUTOMATION] Monthly report sent to Gmail.");
    } catch (error) {
        console.error("❌ [AUTOMATION] Email delivery failed:", error);
    }
});

// --- 3. API ROUTES ---

app.post('/api/login', (req, res) => {
    const { username, password } = req.body;
    if (username === 'admin' && password === 'admin123') {
        res.json({ success: true, token: 'ionet-demo-token-8923' });
    } else {
        res.status(401).json({ success: false, message: 'Invalid credentials' });
    }
});

app.post('/api/rooms', (req, res) => {
    const { roomName } = req.body;
    if (addZone(roomName)) {
        res.json({ success: true, message: `${roomName} added to mesh.` });
    } else {
        res.status(400).json({ success: false, message: 'Room already exists.' });
    }
});

app.delete('/api/rooms/:identifier', (req, res) => {
    const identifier = req.params.identifier;
    if (removeZone(identifier)) {
        res.json({ success: true, message: `${identifier.toUpperCase()} permanently disconnected.` });
    } else {
        res.status(404).json({ success: false, message: `Could not find ${identifier} to delete.` });
    }
});

// Updated for 12 Months
app.get('/api/monthly-savings', (req, res) => {
    const monthlyData = [
        { month: 'Jan', kwhSaved: 850 }, { month: 'Feb', kwhSaved: 920 },
        { month: 'Mar', kwhSaved: 1100 }, { month: 'Apr', kwhSaved: 1250 },
        { month: 'May', kwhSaved: 1400 }, { month: 'Jun', kwhSaved: 1550 },
        { month: 'Jul', kwhSaved: 1700 }, { month: 'Aug', kwhSaved: 1750 },
        { month: 'Sep', kwhSaved: 1600 }, { month: 'Oct', kwhSaved: 1300 },
        { month: 'Nov', kwhSaved: 1050 }, { month: 'Dec', kwhSaved: 950 }
    ];
    res.json({ success: true, data: monthlyData });
});

// --- 4. SOCKET.IO REAL-TIME ENGINE ---
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: "*", methods: ["GET", "POST"] } });

io.on('connection', (socket) => {
    console.log('🔌 Client connected to Socket.io');
    const simulationInterval = setInterval(() => {
        socket.emit('ionet_telemetry', generateNetworkData());
    }, 3000);
    
    socket.on('disconnect', () => {
        console.log('❌ Client disconnected');
        clearInterval(simulationInterval);
    });
});

const PORT = 5001;
server.listen(PORT, () => console.log(`🚀 ClimateSense Backend running on port ${PORT}`));